# This folder holds dependencies needed to build and test the project
# Therefore this folder is used only in configuration stage
# =========================================================

import sys
import os
import stat
import shutil
import urllib
import zipfile
import shlex
import subprocess
import platform

ENGINES = 'dojo'
PLATFORMS = 'android local chrome owa facebook' #list of supported platforms
MARKDOWN = 0 #enable or disable markdown parser dependency
LZSTRING = 0 #enable or disable lz-string dependency
VUNIT_BUGGYFILL = 0 #enable or disable viewport unit buggyfill


#> http://dojotoolkit.org/
DOJO_VERSION = "1.13.0"  #TODO UPDATE
DOJO_URL = "http://download.dojotoolkit.org/release-" + DOJO_VERSION + "/dojo-release-" + DOJO_VERSION + "-src.zip"
DOJO_FILENAME = "dojo-release-" + DOJO_VERSION + "-src.zip"
DOJO_UNZIP = "dojo-release-" + DOJO_VERSION + "-src"
BUILD_PROFILE = "build.profile.js"

#> https://raw.githubusercontent.com/FairyDwarves/pagedown/master/Markdown.Converter.js
MARKDOWN_PARSER_FN = "Markdown.Converter.js"
MARKDOWN_PARSER_URL = "https://raw.githubusercontent.com/FairyDwarves/pagedown/master/" + MARKDOWN_PARSER_FN

#> http://pieroxy.net/blog/pages/lz-string/index.html
LZSTRING_FN = "lz-string-1.3.3.js"
LZSTRING_URL = "https://raw.githubusercontent.com/FairyDwarves/lz-string/master/libs/" + LZSTRING_FN

#> https://github.com/rodneyrehm/viewport-units-buggyfill
VUNIT_BUGGYFILL_FNS = ["viewport-units-buggyfill.js", "viewport-units-buggyfill.hacks.js"]
VUNIT_BUGGYFILL_URI = "https://raw.githubusercontent.com/rodneyrehm/viewport-units-buggyfill/master/"

#list of tools used by the script.
#Add any tools needed in order to check for his existence
tools = {
}
androidTools = {
    "npm" : {"action" : ""},
    "cordova" : {"action" : ""},
}

top = '.'
out = 'wbuild'

def options(opt):
    """ Defines which option can be used for this project """
    gropt = opt.get_option_group('configure options')
    gropt.add_option("-d", "--download", action="store_true", dest="download", default=False, help="force download of depends")
    gropt.add_option('-e', '--engine', action='store', default='dojo', help='engine to configure the build for [default: \'dojo\']', dest='engine')
    gropt.add_option('-p', '--platform', action='store', default='local', help='platform to build for [default: \'local\']', dest='platform')

def configure(conf):
    conf.check_waf_version(mini='1.6.3')
    conf.env.DEPENDS = []
    
    #checking options
    if conf.options.engine not in ENGINES:
      conf.fatal("the --engine options is not recognized. It must be one of : " + ENGINES)  
    conf.env.ENGINE = conf.options.engine #setting up global variable

    if conf.options.platform not in PLATFORMS :
      conf.fatal("The platform " + conf.options.platform + " is unknown. Please use one of " + PLATFORMS)
    conf.env.PLATFORM = conf.options.platform #setting up global variable
        
    #MACROS
    def DL_web(url, filename) :
        """ Download url to filename if --download and needed """
        conf.start_msg("Checking for " + filename)
        dldnode = conf.path.find_node(filename)
        if dldnode is None:
            conf.end_msg("failed", color="RED")
            if conf.options.download == True :
                def progress_report(nb_block, blocksize, totalsize):
                    reportstr = '{}% of {} Bytes'.format(nb_block * blocksize * 100 / totalsize, totalsize)
                    sys.stdout.write("\rDownloading " + filename + " : ")
                    sys.stdout.write(reportstr)
                    sys.stdout.flush()
                sys.stdout.write("Downloading " + filename + " : ... ")
                urllib.urlretrieve(url,conf.path.abspath() + os.sep + filename,progress_report)
                sys.stdout.write("\rDownloading " + filename + " : 100% \n")
                conf.end_msg("ok", color="GREEN")
                urllib.urlcleanup()
                dldnode = conf.path.find_node(filename)
                if dldnode is None : conf.fatal("ERROR : " + filename + " not found.")
            else : conf.fatal(filename + " is not found or invalid.\nPlease run 'waf configure --download'")
        else : conf.end_msg("ok", color="GREEN")
        return dldnode
    
    def unzip(filename, expected_extract, specified_destination=conf.path.srcpath()) :
        conf.start_msg("Checking for " + expected_extract)
        unzipnode = conf.path.find_node(expected_extract)
        if unzipnode is None:
            conf.end_msg("failed", color="RED")
            zipnode = conf.path.find_node(filename)
            if zipnode is not None and zipfile.is_zipfile(zipnode.abspath()):
                with zipfile.ZipFile(zipnode.abspath(),'r') as myzip:
                    conf.start_msg("Unzipping " + expected_extract)
                    myzip.debug = 1
                    myzip.extractall(specified_destination)
                    conf.end_msg("ok", color="GREEN")
            else : 
                conf.fatal("The zip file " + filename + " is not found or invalid.\nPlease run 'waf configure --download'")
            unzipnode = conf.path.find_node(expected_extract)
            if unzipnode is None : conf.fatal("ERROR : Expected " + expected_extract + " not found.")
        else : conf.end_msg("ok", color="GREEN")
        return unzipnode
   
    def npmInstall(package, module, systemWide=False) :
        conf.start_msg("Installing " + package + " via npm into " + module)

        cmd = ''
        if platform.system() == 'Windows' :
            #TODO cmd = 'cmake -G "Visual Studio 12" -DDragonfall_ENABLE_TESTS=ON -DDragonfall_VERSION=' + ctx.env.VERSION + " " + ctx.path.path_from(cmakeBinNode)
            #conf.end_msg("NOT IMPLEMENTED","RED")
            cmd = 'npm install {} {}'.format('-g' if systemWide else '',package)
        elif platform.system() == 'Linux' :
            cmd = '{} npm install {} {}'.format('sudo' if systemWide else '', '-g' if systemWide else '',package)
        elif platform.system() == 'Darwin' : 
            #TODO cmd = 'TODO'
            conf.end_msg("NOT IMPLEMENTED","RED")
        print cmd
        npmproc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            shell=True
        )
        # read line without blocking
        for line in npmproc.stdout :
            sys.stdout.write(line)
    
        npmproc.wait()
        if npmproc.returncode != 0 :
            conf.end_msg("failed : exit status = " + str(npmproc.returncode),"RED")
            conf.fatal("npm failed")
        else:
            if not findTool(package) :
                conf.end_msg("failed","RED")
                conf.fatal("npm succeeded but " + module + " cannot be found.")
                return False
            else :
                conf.end_msg("ok ","GREEN")
                return True
            

    def touch(fname, times=None):
        with file(fname, 'a'):
            os.utime(fname, times)
            
    def findTool(tool):
        try:
            if "path" in tools[tool].keys():
                conf.find_program(tool, path_list = os.path.join(ctx.path.abspath(), tools[tool]["path"]))
            else:
                conf.find_program(tool)
            
            return True
        except conf.errors.ConfigurationError:
            return False
            
    ### End of MACROS ###

    # check tools
    if conf.env.PLATFORM == 'android':
        tools.update(androidTools)
    for tool in tools:
        if not findTool(tool):
            if "cordova" == tool :
                if platform.system() == 'Windows' :
                    cordova_module = '%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\cordova\\cordova.js'
                elif platform.system() == 'Linux' :
                    cordova_module = '/usr/lib/node_modules/cordova/cordova.js'
                elif platform.system() == 'Darwin' :
                    #TODO cmd = 'TODO'
                    conf.end_msg("NOT IMPLEMENTED","RED")
                else: 
                    conf.end_msg("NOT IMPLEMENTED","RED")
                    
                if not os.path.isfile(cordova_module) :
                    npmInstall('cordova',cordova_module,True)
                    
            else :
                conf.fatal('Cannot find \"' + tool + '\"! Please install it prior to continue.')

    if MARKDOWN :
        #download Markdown 2 html parser
        DL_web(MARKDOWN_PARSER_URL,MARKDOWN_PARSER_FN)
        conf.env.DEPENDS.append(MARKDOWN_PARSER_FN)

    if LZSTRING :
        #download LZ-String
        DL_web(LZSTRING_URL,LZSTRING_FN)
        conf.env.DEPENDS.append(LZSTRING_FN)

    if VUNIT_BUGGYFILL :
        #download viewport units buggyfill
        for toDldFN in VUNIT_BUGGYFILL_FNS :
            DL_web(VUNIT_BUGGYFILL_URI + toDldFN, toDldFN)
            conf.env.DEPENDS.append(toDldFN)
    
    if conf.env.PLATFORM == 'android' :
    
        def detect_android() :
            conf.start_msg("=> Android SDK tools/ should be in your PATH")
            android_detect = subprocess.Popen("android -h",
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                shell=True,)
            out,err = android_detect.communicate()
            # for unknown reason this command returns 1 on linux but 0 on windows...
            if (os.name == 'posix' and android_detect.returncode == 1) or (os.name == 'nt' and android_detect.returncode == 0):
                conf.to_log(out)
                conf.to_log(err)    
                conf.end_msg("ok","GREEN")
                    
                conf.start_msg("=> Android SDK tools-platform/ should be in your PATH")
                adb_detect = subprocess.Popen("adb version",
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    shell=True,)
                out,err = adb_detect.communicate()
                if adb_detect.returncode == 0 :
                    conf.to_log(out)
                    conf.to_log(err)
                    conf.end_msg("ok","GREEN")
                    return True
                else :
                    conf.end_msg("failed","RED")
                    conf.fatal("Command Output : \n" + out + "Error :\n" + err)
            else :
                conf.end_msg("failed","RED")
                conf.fatal("Command Output : \n" + out + "Error :\n" + err)

        def detect_javac() :
            conf.start_msg("=> Java JDK bin/ should be in your PATH")
            javac_detect = subprocess.Popen("javac -version",
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                shell=True,)
            out,err = javac_detect.communicate()
            if javac_detect.returncode == 0 :
                conf.to_log(out)
                conf.to_log(err)
                conf.end_msg("ok","GREEN")
                return True
            else :
                conf.end_msg("failed","RED")
                conf.fatal("Command Output : \n" + out + "Error :\n" + err)
            
        def detect_ant() :
            conf.start_msg("=> Apache ant bin/ should be in your PATH")
            ant_detect = subprocess.Popen("ant -version",
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                shell=True,)
            out,err = ant_detect.communicate()
            if ant_detect.returncode == 0 :
                conf.to_log(out)
                conf.to_log(err)
                conf.end_msg("ok","GREEN")
                return True
            else :
                conf.end_msg("failed","RED")
                conf.fatal("Command Output : \n" + out + "Error :\n" + err)
            
        #checking all is there
        conf.start_msg("Android build platform setup: ")
        if detect_android() and detect_javac() and detect_ant():
            conf.end_msg("ok","GREEN")
        else:
            conf.end_msg("failed","RED")
        
    #end of conf.env.PLATFORM
        pass

    if conf.env.ENGINE == "dojo" :

        DL_web(DOJO_URL,DOJO_FILENAME)
        dojonode = unzip(DOJO_FILENAME,DOJO_UNZIP)
        conf.env.DOJOPATH = dojonode.abspath()
    
        #check if a profile exists
        conf.start_msg("Checking for build profile")
        profnode = conf.path.find_node(BUILD_PROFILE)
        if profnode is None : # if not creates it
            conf.end_msg("failed", color="RED")
            touch(BUILD_PROFILE)
            if conf.path.find_node(BUILD_PROFILE) is None : conf.fatal("Unable to create blank build profile : " + BUILD_PROFILE)
            else: conf.msg("Blank " + BUILD_PROFILE + " created")
        else : conf.end_msg("ok",color="GREEN")

        
        conf.env.DEPENDS.append(DOJO_UNZIP)

    else : # NOT POSSIBLE, default should be dojo
        conf.fatal("SHOULD NOT REACH HERE")
        pass
    #end of conf.env.ENGINE

def build(bld):
    #send back needed vars
    bld.env.DOJO_UNZIP = DOJO_UNZIP
    bld.env.BUILD_PROFILE = BUILD_PROFILE
    bld.env.MARKDOWN = MARKDOWN
    bld.env.LZSTRING = LZSTRING
